# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: a
  steps:
  - checkout: none
    fetchDepth: 1
  - bash: |
      which bash
      ls
      ls /
      uname -a
      id
      cat /etc/issue
      cat /etc/issue.net
      python3 --version
      pip3 install setuptools wheel
      pip3 install west
      echo $PATH
      export PATH=$HOME/.local/bin:$PATH
      echo $PATH
      west -v
    displayName: Multiline Bash script
    env:
      name: Microsoft