# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  containers:
  - container: zephyr # reusable alias
    image: zephyrprojectrtos/ci:v0.9.3

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: a
  container: zephyr # reference
  steps:
  - bash: |
      which bash
      echo Hello $name
    displayName: Multiline Bash script
    env:
      name: Microsoft