# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: a
  steps:
  - checkout: self
    fetchDepth: 1
    path: zephyr
  - bash: |
      which bash
      ls
      ls /
      pwd
      uname -a
      id
      cat /etc/issue
      cat /etc/issue.net
      python3 --version
      pip3 install setuptools wheel
      pip3 install west
      echo $PATH
      export PATH=$HOME/.local/bin:$PATH
      echo $PATH
      source zephyr-env.sh
      west --version
      cd ..
      west init -l zephyr || true
      cd zephyr
      west update
      export CITOOLS=$(west list ci-tools -f"{abspath:18}")
      echo $CITOOLS
      sudo pip3 install -r ${CITOOLS}/requirements.txt


    displayName: Multiline Bash script
    env:
      name: Microsoft