version: 2.1
jobs:
  build:
    environment:
      ZEPHYR_SDK_INSTALL_DIR: /opt/sdk/zephyr-sdk-0.10.3
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
    docker: 
      - image: zephyrprojectrtos/ci:v0.10.1
    steps:
      - checkout:
           path: zephyr
      - run:
          command: |
            pwd
            ls
            ls zephyr
            export

