version: 2.1
jobs:
  build:
    docker: 
      - image: zephyrprojectrtos/ci:v0.10.1
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: |
            pwd
            ls

