version: 2.1
jobs:
  build:
    environment:
      ZEPHYR_SDK_INSTALL_DIR: /opt/sdk/zephyr-sdk-0.10.3
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
    docker: 
      - image: zephyrprojectrtos/ci:v0.10.1
    steps:
      - checkout:
           path: zephyr
      - run:
          command: |
            pwd
            ls
            ls zephyr
            export HELLO=$(($CIRCLE_NODE_INDEX+1))
            export
            ln -s /opt/modules
            ln -s /opt/tools
            id
            cd zephyr
            cat /proc/cpuinfo
            ./scripts/ci/run_ci.sh -c -b ${CIRCLE_BRANCH} -r origin -m 80 -M 1000
            ls
            ls sanity-out
            ls sanity-out.1
      - store_test_results:
           path: ~/zephyr/sanity-out

