version: 2.1
jobs:
  build:
    environment:
      ZEPHYR_SDK_INSTALL_DIR: /opt/sdk/zephyr-sdk-0.10.3
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
    docker: 
      - image: zephyrprojectrtos/ci:v0.10.1
    steps:
      - checkout:
           path: zephyr
      - run:
          command: |
            pwd
            ls
            ls zephyr
            export
            cd zephyr
            ./scripts/ci/run_ci.sh -c -b ${CIRCLE_BRANCH} -r origin -m ${CIRCLE_NODE_TOTAL} -M ${CIRCLE_NODE_TOTAL};

