name: C/C++ CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://zephyrprojectrtos/zephyr-build:latest
    - name: environment
      run: env
